services:
  sonarr:
    image: ghcr.io/hotio/sonarr
    environment:
      PUID: "1000"
      PGID: "1000"
      UMASK: "002"
      TZ: "Etc/UTC"
      WEBUI_PORTS: "8989/tcp"
    volumes:
      - sonarr-config:/config
      - sonarr-data:/data
      - /mnt/user/Plex:/Plex
    networks:
      - traefik_proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == Apollo
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      labels:
        - "homepage.name=Sonarr"
        - "homepage.group=Media"
        - "homepage.icon=sonarr"
        - "homepage.href=https://sonarr.parke.dev"
        - "traefik.enable=true"
        # HTTPS router
        - "traefik.http.routers.sonarr.rule=Host(`sonarr.parke.dev`)"
        - "traefik.http.routers.sonarr.entrypoints=websecure"
        - "traefik.http.routers.sonarr.tls=true"
        # HTTP router (redirect to HTTPS)
        - "traefik.http.routers.sonarr-http.rule=Host(`sonarr.parke.dev`)"
        - "traefik.http.routers.sonarr-http.entrypoints=web"
        - "traefik.http.routers.sonarr-http.middlewares=https-redirect@swarm"
        # Service port
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

volumes:
  sonarr-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/user/appdata/sonarr/config

  sonarr-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/user/appdata/sonarr/data

networks:
  traefik_proxy:
    external: true
    name: traefik_traefik_proxy
