services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    networks:
      - traefik_proxy
    volumes:
      - type: volume
        source: nfs-data
        target: /app/config
        volume:
          subpath: homepage/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.parke.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    deploy:
      placement:
        constraints:
          - node.hostname != Apollo
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      labels:
        - "traefik.enable=true"
        # HTTPS router
        - "traefik.http.routers.homepage.rule=Host(`homepage.parke.dev`)"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        - "traefik.http.routers.homepage.tls=true"
        # HTTP router (redirect to HTTPS)
        - "traefik.http.routers.homepage-http.rule=Host(`homepage.parke.dev`)"
        - "traefik.http.routers.homepage-http.entrypoints=web"
        - "traefik.http.routers.homepage-http.middlewares=https-redirect@swarm"
        # Service port
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"

volumes:
  nfs-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.10.10.215,rw,nfsvers=3,soft"
      device: ":/mnt/user/swarm-data"

networks:
  traefik_proxy:
    external: true
    name: traefik_traefik_proxy
