services:
  portainer:
    image: portainer/portainer-ce:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - type: volume
        source: nfs-data
        target: /data
        volume:
          subpath: portainer/data
    networks:
      - traefik_proxy
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname != Apollo
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      labels:
        - "traefik.enable=true"
        # HTTPS router
        - "traefik.http.routers.portainer.rule=Host(`portainer.parke.dev`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        # HTTP router (redirect to HTTPS)
        - "traefik.http.routers.portainer-http.rule=Host(`portainer.parke.dev`)"
        - "traefik.http.routers.portainer-http.entrypoints=web"
        - "traefik.http.routers.portainer-http.middlewares=https-redirect@swarm"
        # Service port
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  agent:
    image: portainer/agent:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

volumes:
  nfs-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.10.10.215,rw,nfsvers=3,soft"
      device: ":/mnt/user/swarm-data"

networks:
  traefik_proxy:
    external: true
    name: traefik_traefik_proxy
  agent_network:
    driver: overlay
    attachable: true
